location /api/remote/backups/ {
    gzip off;
    client_max_body_size 0;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    send_timeout       3600s;
    include conf.d/include/proxy.conf;
}

location /wings-proxy/ {
    gzip off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    send_timeout       3600s;
    include conf.d/include/proxy.conf;
}
